Repository ResultadosDigitais/matrix, pull requests merged in 2019-04, with the labels that each got.

#37 Create enhancement request template
  .github/ISSUE_TEMPLATE/enhancement_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: need review

#54 fix the broadcast to sync room for current logged user
  controllers/office.controller.js
  office.server.js
  public/office.web.js
Labels: kind: bug, kind: enhancement

#60 create a mechanism to identify url room, if th url room is not present…
  public/office.web.js
Labels: kind: enhancement, kind: feature
