Repository ResultadosDigitais/matrix, pull requests merged in 2019-05, with the labels that each got.

#127 Add Pull Request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind: enhancement

#130 returning message whats'up surname in the header
  package-lock.json
  public/js/header.js
Labels: kind: ux debt

#134 Office web clean up
  public/js/office.web.js
Labels: kind: tech debt

#133 improve to 100% office.controller.js code coverage
  test/controllers/office.controller.test.js
Labels: kind: tech debt

#128 Avoid close meet modal by mistake
  public/js/office.web.js
  views/office.ejs
Labels: kind: enhancement

#114 add webnotification to ask user to join in room
  public/js/office.web.js
Labels: kind: enhancement, kind: ux debt

#138 Fix firefox responsive iframe
  public/css/office.css
  public/js/office.web.js
  views/office.ejs
Labels: kind: bug

#140 fix get menu using webpack
  frontend/office.js
Labels: kind: bug, priority: high

#144 improve profile.js test from 55% to 100%
  frontend/office.js
  test/frontend/profile.test.js
Labels: kind: tech debt

#161 Build production server
  .circleci/config.yml
  .gitignore
  Dockerfile
  backend/app.server.js
  backend/controllers/google.credentials.controller.js
  backend/controllers/office.controller.js
  backend/controllers/rooms.controller.js
  backend/office.server.js
  docker-entrypoint.sh
  package-lock.json
  package.json
  test/app.server.test.js
  test/controllers/google.credentials.controller.test.js
  test/controllers/office.controller.test.js
Labels: kind: tech debt, priority: medium

#162 Assets cache invalidation
  backend/app.server.js
  backend/controllers/assets.controller.js
  package-lock.json
  package.json
  test/app.server.test.js
  views/index.ejs
  views/office.ejs
  webpack.common.js
Labels: kind: enhancement
