Repository ResultadosDigitais/matrix, pull requests merged in 2020-03, with the labels that each got.

#237 Add a license file that github understant
  LICENSE
Labels: kind: enhancement

#252 Ajusta a notificação para navegadores que não possui suporte
  frontend/src/components/NotificationCheckbox.js
  frontend/src/notification.js
Labels: kind: bug, priority: high

#253 New fix for Notification
  frontend/src/notification.js
Labels: kind: bug
