Repository ResultadosDigitais/matrix, pull requests merged in 2020-04, with the labels that each got.

#285 init All Contributors
  .all-contributorsrc
  README.md
  package.json
  yarn.lock
Labels: kind: enhancement

#235 Improve backend routes auth
  backend/app/app.auth.js
  backend/app/app.config.js
  backend/app/app.routes.js
  backend/app/app.server.js
  backend/app/controllers/google.credentials.controller.js
  backend/app/helpers/security.js
  backend/app/index.js
  backend/app/middlewares/authenticate.js
  backend/app/middlewares/authentication.js
  backend/app/services/auth/authorization.js
  backend/app/services/auth/index.js
  backend/app/services/auth/strategy.js
  backend/app/views/index.ejs
  backend/app/views/morpheus.ejs
  backend/package-lock.json
  backend/package.json
  backend/test/app.server.test.js
  backend/test/controllers/google.credentials.controller.test.js
  backend/test/helpers/secutiry.test.js
  backend/test/services/auth/authorization.test.js
  backend/test/services/auth/strategy.test.js
  frontend/src/header.css
  frontend/src/header.js
  frontend/src/morpheus.js
  frontend/src/pages/login/google-button/index.js
  frontend/src/pages/login/google-button/index.module.css
  frontend/src/pages/login/login.js
Labels: kind: bug, kind: tech debt, security

#304 Add ROOMS_DATA and ROOMS_SOURCE at variables.env.example
  variables.example.env
Labels: kind: bug

#311 Feature health rooms
  backend/app/app.healthcheck.js
  backend/app/app.healthcheck.test.js
  backend/app/app.server.js
  backend/app/controllers/rooms.controller.js
  backend/app/services/room.test.js
  backend/app/services/rooms.js
  backend/package-lock.json
  backend/package.json
Labels: kind: enhancement, need review
